# Generated by Django 2.2.16 on 2020-10-11 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Enter the book's title", max_length=50)),
                ('isbn', models.CharField(blank=True, help_text='Enter the 13 number ISBN, if applicable', max_length=13, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('author', models.CharField(help_text='Enter author name, if applicable (just one)', max_length=40)),
                ('edition', models.PositiveSmallIntegerField(help_text='Enter edition number')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('f', 'Like New'), ('nf', 'Near Fine'), ('vg', 'Very Good'), ('g', 'Good'), ('fr', 'Fair'), ('p', 'Poor')], max_length=2)),
                ('purchase_price', models.IntegerField(blank=True, null=True)),
                ('rental_price', models.IntegerField(blank=True, null=True)),
                ('negotiable', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_trader.Book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter school name here', max_length=40)),
                ('primary_color', models.CharField(default='#ff6347', max_length=7)),
                ('secondary_color', models.CharField(default='#ff6347', max_length=7)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_asking_price', models.IntegerField(blank=True, null=True)),
                ('purchase_asking_price', models.IntegerField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_trader.Listing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
