# Generated by Django 3.1.3 on 2020-12-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursebook',
            old_name='semeseter',
            new_name='semester',
        ),
    ]
