# Generated by Django 3.1.3 on 2020-11-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0002_auto_20201027_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
