# Generated by Django 3.1.3 on 2020-11-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0003_auto_20201125_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='listing',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
