# Generated by Django 3.1.3 on 2020-12-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0003_auto_20201206_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text="Enter the book's title", max_length=100),
        ),
    ]
