# Generated by Django 3.1.3 on 2020-11-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0004_auto_20201125_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
