# Generated by Django 3.1.3 on 2020-11-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0005_auto_20201125_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='Enter the 13 number ISBN, if applicable', max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(help_text='Enter school name here', max_length=40, unique=True),
        ),
    ]
