# Generated by Django 3.1.3 on 2020-12-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0005_book_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmessage',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
