# Generated by Django 3.1.3 on 2020-12-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0006_requestmessage_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmessage',
            name='is_seller',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
