# Generated by Django 3.1.3 on 2020-11-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0006_auto_20201126_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomer',
            name='first_name',
            field=models.CharField(default='Corey', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercustomer',
            name='last_name',
            field=models.CharField(default='Bean', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingrequest',
            name='purchase_asking_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='listingrequest',
            name='rental_asking_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
