# Generated by Django 3.1.3 on 2020-11-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0007_auto_20201126_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_name',
            new_name='name',
        ),
    ]
