# Generated by Django 3.1.3 on 2020-12-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0007_auto_20201206_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='text_trader.school'),
        ),
    ]
