# Generated by Django 3.1.3 on 2020-11-27 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0008_auto_20201126_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='locality_id',
            new_name='locality',
        ),
    ]
