# Generated by Django 3.1.3 on 2020-11-27 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0009_auto_20201126_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='text_trader.usercustomer'),
        ),
    ]
