# Generated by Django 3.1.3 on 2020-11-29 20:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text_trader', '0011_auto_20201129_1436'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCustomer',
            new_name='Customer',
        ),
    ]
