# Generated by Django 3.1.3 on 2020-12-29 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0011_auto_20201228_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmessage',
            name='is_seller',
        ),
    ]
