# Generated by Django 3.1.3 on 2020-11-30 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0012_auto_20201129_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingRequests', to='text_trader.customer'),
        ),
    ]
