# Generated by Django 3.1.3 on 2020-12-31 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0012_remove_requestmessage_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingsearch',
            name='customer',
        ),
        migrations.AddField(
            model_name='listingsearch',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='text_trader.customer'),
        ),
        migrations.AddField(
            model_name='listingsearch',
            name='requested',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
