# Generated by Django 3.1.3 on 2020-12-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0013_auto_20201231_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
