# Generated by Django 3.1.3 on 2021-01-03 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0014_auto_20210102_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingsearch',
            name='customer',
        ),
        migrations.AddField(
            model_name='listing',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listingsearch',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listingsearch',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='text_trader.customer'),
        ),
        migrations.AddField(
            model_name='listingsearch',
            name='requested',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, error_messages={'unique': 'A book with this ISBN already exists.'}, help_text='Enter the 10 number ISBN, if applicable', max_length=13, null=True, unique=True),
        ),
    ]
