# Generated by Django 3.1.3 on 2020-12-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0014_listing_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingsearch',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
