# Generated by Django 3.1.3 on 2021-01-03 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0016_listingsearch_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('satisfied', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_request_set', to='text_trader.book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_trader.customer')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_trader.school')),
            ],
        ),
    ]
