# Generated by Django 3.1.3 on 2021-01-05 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0017_notificationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrequest',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='text_trader.customer'),
        ),
    ]
