# Generated by Django 3.1.3 on 2021-01-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0018_auto_20210105_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='purchase_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='listingrequest',
            old_name='purchase_asking_price',
            new_name='asking_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='rental_price',
        ),
        migrations.RemoveField(
            model_name='listingrequest',
            name='rental_asking_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_for_rent',
            field=models.BooleanField(default=False),
        ),
    ]
