# Generated by Django 3.1.3 on 2021-01-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0019_auto_20210105_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
