# Generated by Django 3.1.3 on 2021-01-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_trader', '0020_requestmessage_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
